nginx:
  image: nginx:1.13.2-alpine
  links:
    - api
    - icecast
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - < ROUTE TO SSL CERTIFICATES >:/usr/src/app/certs:ro
    - ./config/:/etc/nginx/conf.d

api:
  image: darkade/slacktunes-api:8.1.2-alpine # ../slacktunes-api #
  expose:
    - "4390"
  environment:
    - MOPIDYURL=mopidy
    - MOPIDYPORT=6680
    - SLACKID=< SLACK APP ID >
    - SLACKSECRET=< SLACK APP SECRET >
    - SLACKHOOK=< SLACK WEBHOOK URL>
    - LISTENURL=< ICECAST LISTEN URL >
  links:
    - mopidy

mopidy:
  image: darkade/mopidy:alpine2.1.0-r1 #../docker-mopidy #
  expose:
    - "6680"
  links:
    - icecast
  environment:
    - ICECAST_SOURCE_PASSWORD=< ICECAST SOURCE PASSWORD >
  entrypoint:
    - mopidy
    - -o audio/output=lamemp3enc ! shout2send mount=mopidy ip=icecast port=8000 password=$ICECAST_SOURCE_PASSWORD

icecast:
  image: darkade/icecast:alpine3.6
  environment:
    - ICECAST_SOURCE_PASSWORD=< ICECAST_SOURCE_PASSWORD >
    - ICECAST_RELAY_PASSWORD=< ICECAST_RELAY_PASSWORD >
    - ICECAST_ADMIN_PASSWORD=< ICECAST_ADMIN_PASSWORD >
  expose:
    - "8000"
